// Mirrors service/configuration_encoder.dart — converts a Server profile
// into the TOML string that vpn_easy_start() expects.

import type { Server } from "./types";

export function encodeConfig(server: Server): string {
  const protocol = server.protocol;
  const fallback = server.fallbackProtocol ?? "";

  const addresses = server.ipAddress
    ? `["${normalizeAddress(server.ipAddress)}"]`
    : `["${normalizeAddress(server.domain)}"]`;

  const dnsUpstreams = toTomlList(server.dnsUpstreams);
  const excludedRoutes = toTomlList(server.excludedRoutes);
  const includedRoutes = toTomlList(server.includedRoutes);

  const cert = server.certificate
    ? `"\n${server.certificate}\n"`
    : `""`;

  return `\
# Generated by TrustTunnel GUI
loglevel = "info"
vpn_mode = "general"
killswitch_enabled = ${server.killSwitch}
post_quantum_group_enabled = ${server.postQuantum}
exclusions = ${excludedRoutes}
dns_upstreams = ${dnsUpstreams}

[endpoint]
hostname = "${server.domain}"
addresses = ${addresses}
has_ipv6 = false
username = "${server.username}"
password = "${server.password}"
client_random = ""
skip_verification = ${server.skipVerification}
certificate = ${cert}
upstream_protocol = "${protocol}"
upstream_fallback_protocol = "${fallback}"
anti_dpi = ${server.antiDpi}

[listener]

[listener.tun]
included_routes = ${includedRoutes}
excluded_routes = ${excludedRoutes}
mtu_size = ${server.mtuSize}
`;
}

function normalizeAddress(addr: string): string {
  // Append :443 if no port is present.
  const isIpv6 = (addr.match(/:/g) ?? []).length > 1;
  if (isIpv6) {
    // Already has port if it matches [addr]:port
    if (/\]:\d+$/.test(addr)) return addr;
    return `[${addr}]:443`;
  }
  if (addr.includes(":")) return addr; // already has port
  return `${addr}:443`;
}

function toTomlList(items: string[]): string {
  return `[${items.map((i) => `"${i}"`).join(", ")}]`;
}
